### ISSUE TITLE
Italian language json

### ISSUE THREAD

**Issue by Cydior77** [ThomasVon2021/blikvm-web-client#8]
Good morning, I translated the en.json file into Italian.
I wish I could put it in the program. can I send it to you?
[IT.json](https://github.com/user-attachments/files/17490818/IT.json)

**Comment by ThomasVon2021** [comment]
Thank you very much. Can you propose a PR to merge it?

**Comment by Cydior77** [comment]
I'll try, I'm not very good at github :)

**Comment by ThomasVon2021** [comment]
If you can't figure it out, please let me know and I can directly download your file and push it to the repository. If you are referring to PR, this document will always have records of your submissions, making it more meaningful.

**Comment by Cydior77** [comment]
I'll try to attach it here

[IT.json](https://github.com/user-attachments/files/17517091/IT.json)

**Comment by ThomasVon2021** [comment]
<img width="720" alt="截屏2024-10-28 20 18 50" src="https://github.com/user-attachments/assets/6fd98657-fcab-4631-a89e-9e99a62d1d95">
v1.4.9 added.
