### ISSUE TITLE
Ukrainian translation

### ISSUE THREAD

**Issue by otkachov** [ThomasVon2021/blikvm-web-client#9]
Hi,
First of all, I want to say thank you to the developer for the great product!

I made a translation from English to my language Ukrainian.
Could you add Ukrainian to the next release, please?

File attached.
[UA.json](https://github.com/user-attachments/files/17735316/UA.json)

**Comment by ThomasVon2021** [comment]
Sure, thanks.

**Comment by ThomasVon2021** [comment]
I have some updates today. Would you like to submit another version after I update them?

**Comment by otkachov** [comment]
Of course.
I will try to add via PR.
Thank you!

**Comment by otkachov** [comment]
Done.
